// 语言配置
const translations = {
    zh: {
        'nav-home': '首页',
        'nav-about': '关于我们',
        'nav-products': '产品展示',
        'nav-culture': '合作关系',
        'nav-esg': '联系我们',
        'nav-career': '职业发展',
        'nav-contact': '联系我们',
        'hero-title': '领先的智能产品和服务提供商',
        'hero-subtitle': '用科技为社会创造新价值',
        'about-title': '关于我们',
        'about-subtitle': 'ABOUT US',
        'about-content': 'KGD Group 成立于 1999 年，总部位于香港沙田。KGD 集团已发展成为一家集开发、制造和采购服务为一体的配套工业公司。技术力量雄厚，生产设备齐全，检测齐全。主要产品：各种手机、平板电脑等产品的模切件，以及精密铜、不锈钢和绝缘材料的冲压件、铝合金铸件、锌合金压铸件、工业塑料袋、拉伸膜等。公司采用国际最先进的生产设备和检测设备，为客户提供最优质的产品。公司已通过ISO 9001和ISO 14001认证，是国际市场上专业精冲和模切产品的主要供应商。',
        'company-intro': 'KGD 集团已发展成为一家集开发、制造和采购服务于一体的综合性工业公司。公司采用最先进的国际生产设备和检测设备，为客户提供最优质的产品。是国际市场上专业精密冲压和模切产品的主要供应商。',
        'company-history-title': '发展历程',
        'history-2002-title': '公司成立',
        'history-2002-content': '科技在上海成立，开始专注于移动通信产品的研发和制造。',
        'history-2010-title': '业务扩展',
        'history-2010-content': '成功拓展智能终端产品线，成为行业领先的智能产品解决方案提供商。',
        'history-2020-title': '技术创新',
        'history-2020-content': '建立全球研发中心，推动5G、AI等前沿技术的创新应用。',
        'advantages-title': '核心优势',
        'advantage-tech': '技术创新',
        'advantage-tech-content': '拥有强大的研发团队和先进的技术平台，持续推动产品创新。',
        'advantage-manufacture': '智能制造',
        'advantage-manufacture-content': '采用先进的智能制造系统，确保产品质量和生产效率。',
        'advantage-global': '全球布局',
        'advantage-global-content': '建立全球化的研发、生产和销售网络，服务全球客户。',
        'products-title': '产品展示',
        'product1-title': '压铸模具',
        'product2-title': '塑料拉伸膜',
        'product3-title': '硬件展示',
        'product1-desc': '高精度压铸模具，广泛应用于各类工业产品的制造，具备优良的耐用性和精密度。',
        'product2-desc': '高强度塑料拉伸膜，适用于包装、保护和运输各类产品，具有良好的延展性和韧性。',
        'product3-desc': '多样化精密五金件，广泛应用于电子、机械等领域，满足客户多样化需求。',
        'culture-title': '合作关系',
        'culture-subtitle': 'partnership',
        'culture-vision': '我们的愿景',
        'culture-vision-content': '成为领先的智能产品和服务提供商',
        'culture-mission': '我们的使命',
        'culture-mission-content': '用科技为社会创造新价值',
        'culture-values': '核心价值观',
        'culture-values-content': '以客户为中心，以贡献者为本，长期主义',
        'career-title': '职业发展',
        'career-subtitle': '携手 成就未来',
        'career-philosophy': '我们倡导："以贡献者为本"，并将其贯穿于人才评价、发展、激励等管理活动中。我们已经逐步形成基于任职资格、绩效评价体系，薪酬激励体系的"招、训、报、考、留"全流程人才管理体系、对人定岗、定级、定薪、定晋升通道。同时，我们采用AI组织进行人事审议和决策，提升人事决策的"公平、公正、避免人事决策一言堂"。',
        'career-development-title': '人才培养',
        'career-development-content': '我们将在工能力成长投入更多的资源和努力。学院和9个专业学院通过专项巡展帮助校招生、新员工和各层级干部快速融入和胜任，为各领域培养专业人才。我们正在开发更加精准、系统化的学习平台，覆盖所有岗位的知识库库，打造学习化学习型组织，帮助大家一起成长。',
        'career-plan-title': '发展计划',
        'career-plan-content': '我们将继续推广活水计划，打造内部市场化的人才流动机制，支持在同一个岗位上超过三年的员工轮岗，通过轮岗提升和丰富人员能力。',
        'copyright': 'Copyright©2016上海科技股份有限公司 版权所有',
        'smartphone-title': '智能手机',
        'product-planning-title': '产品规划',
        'product-planning-content': '新产品研发完全贴合市场需求，切实落实用户体验，外观工艺设计、功能定义优化，系统量身定制，根据市场动态进行产品规划调整，打好时间差，打造差异化产品定位，匠心打造精品。',
        'tech-innovation-title': '技术创新与研发',
        'tech-innovation-content': '结合精密工艺标准，高分子复合材料体系，智能算法设计，形态新颖的结构，更加贴心的设计，更加个性化的体验；通过自主开发的多元化软件系统，实现了手机自适应的弹幕展示和功能的联动。',
        'platform-title': '全面覆盖的方案平台',
        'platform-content': '打造从入门到旗舰级全平台解决方案，覆盖所有档位移动终端需求，支持快速定制化开发及量产。',
        'quality-title': '质量管理',
        'quality-content': '智能检测技术和各项原材料检验行业标准为依据，检测流程分析管理和CQA改进认证，并有ISO/IEC17025级实验室和专业技术检测团队，全面提升产品质量和服务品质。',
        'esg-title': '可持续发展与ESG',
        'esg-subtitle': 'SUSTAINABLE DEVELOPMENT & ESG',
        'esg-strategy-title': 'ESG策略与机制',
        'esg-strategy-content': '我们致力于将ESG理念融入企业发展战略，通过建立完善的ESG管理体系，推动企业可持续发展，为社会创造长期价值。',
        'esg-governance-title': 'ESG治理体系',
        'governance-level-1': '战略层',
        'governance-level-1-content': '董事会对ESG战略和汇报承担全面责任',
        'governance-level-2': '管理层',
        'governance-level-2-content': 'ESG委员会负责ESG日常管理工作',
        'governance-level-3': '执行层',
        'governance-level-3-content': '各职能部门负责具体ESG工作的执行',
        'esg-performance-title': '2024年关键绩效一览',
        'performance-env': '环境：守望地球',
        'performance-env-1': '• 碳排放强度下降15%',
        'performance-env-2': '• 可再生能源使用率提升20%',
        'performance-env-3': '• 废弃物回收率达95%',
        'performance-social': '社会：共创价值',
        'performance-social-1': '• 员工培训覆盖率100%',
        'performance-social-2': '• 供应商ESG评估覆盖率90%',
        'performance-social-3': '• 社区公益投入500万元',
        'performance-gov': '治理：稳健发展',
        'performance-gov-1': '• 董事会成员多元化比例40%',
        'performance-gov-2': '• 反腐败培训覆盖率100%',
        'performance-gov-3': '• 信息安全事件0发生',
        'esg-reports-title': '报告与文件',
        'report-2024': '科技2024年ESG报告',
        'download-report': '下载报告',
        'contact-title': '联系我们',
        'contact-subtitle': 'CONTACT US',
        'contact-address-title': '公司地址',
        'contact-address': '香港新界沙田火炭桂地街10-14號華麗工業中心11楼6室',
        'contact-phone-title': '联系电话',
        'contact-phone': 'Tel.:(852)3188447、31884564 Fax:(852)31884152',
        'contact-email-title': '电子邮箱',
        'contact-email': 'kgd@kgdcor.com',
        'contact-form-title': '给我们留言',
        'contact-submit': '发送留言',
        'contact-name-placeholder': '您的姓名',
        'contact-email-placeholder': '您的邮箱',
        'contact-subject-placeholder': '主题',
        'contact-message-placeholder': '您的留言',
        'employee-dev-title': '员工发展',
        'dev-training': '培训体系',
        'dev-training-content': '完善的培训体系，助力员工成长',
        'dev-career': '职业发展',
        'dev-career-content': '清晰的晋升通道，实现职业理想',
        'dev-environment': '工作环境',
        'dev-environment-content': '舒适的工作环境，激发创新活力',
        'dev-benefits': '福利待遇',
        'dev-benefits-content': '优厚的福利待遇，保障员工权益',
        'activities-title': '企业活动',
        'activity-team': '团建活动',
        'activity-team-content': '丰富多彩的团建活动，增进团队凝聚力',
        'activity-culture': '文化活动',
        'activity-culture-content': '多元化的文化活动，丰富员工生活',
        'activity-charity': '公益活动',
        'activity-charity-content': '积极履行社会责任，参与公益事业',
        'culture-innovation': '创新文化',
        'culture-innovation-content': '鼓励创新思维，拥抱变革，持续突破技术边界，为客户创造更大价值。',
        'culture-innovation-1': '• 创新实验室',
        'culture-innovation-2': '• 技术研讨会',
        'culture-innovation-3': '• 创新项目孵化',
        'culture-collaboration': '协作文化',
        'culture-collaboration-content': '倡导开放合作，跨部门协同，打造高效团队，实现共同目标。',
        'culture-collaboration-1': '• 跨部门项目组',
        'culture-collaboration-2': '• 团队建设活动',
        'culture-collaboration-3': '• 知识分享平台',
        'work-env-title': '工作环境',
        'env-office': '现代化办公环境',
        'env-office-content': '宽敞明亮的办公空间，配备先进的办公设施，为员工提供舒适的工作环境。',
        'env-leisure': '休闲娱乐空间',
        'env-leisure-content': '健身房、休息室、咖啡吧等休闲设施，让员工在工作之余得到充分放松。',
        'env-lab': '创新研发中心',
        'env-lab-content': '配备先进设备的研发实验室，为技术创新提供最佳环境。',
        'main-equipment-title': '主要设备',
        'service-flow-title': '服务流程',
        'service-step1-title': '产品设计',
        'service-step1-desc': '根据客户需求进行专业产品设计。',
        'service-step2-title': '样品寄送',
        'service-step2-desc': '为客户提供样品进行确认。',
        'service-step3-title': '签订承认书',
        'service-step3-desc': '客户确认样品后签订承认书。',
        'service-step4-title': '签订合同',
        'service-step4-desc': '双方签订正式合作合同。',
        'service-step5-title': '监督生产',
        'service-step5-desc': '全程监督生产进度与质量。',
        'service-step6-title': '品质保证',
        'service-step6-desc': '严格质检，确保产品品质。',
        'service-step7-title': '货物运输',
        'service-step7-desc': '支持海运、空运、陆运多种运输方式。',
        'service-step8-title': '售后服务',
        'service-step8-desc': '专人跟进，及时响应客户需求。',
        'footer-company-name': '金川電装有限公司',
        'footer-contact-info': 'Tel.:(852)3188447、31884564 Fax:(852)31884152',
        'footer-email': 'kgd@kgdcor.com',
        'footer-address': '香港新界沙田火炭桂地街10-14號華麗工業中心11楼6室',
        'footer-quick-links': '快速链接',
        'footer-copyright': '版权所有'
    },
    en: {
        'nav-home': 'Home',
        'nav-about': 'About',
        'nav-products': 'Products',
        'nav-culture': 'Partnership',
        'nav-esg': 'ESG',
        'nav-career': 'Career',
        'nav-contact': 'Contact Us',
        'hero-title': 'Leading Smart Products and Services Provider',
        'hero-subtitle': 'Creating New Value for Society Through Technology',
        'about-title': 'About Us',
        'about-subtitle': 'ABOUT US',
        'about-content': 'KGD Group Since 1999 and is headquartered in the Hong Kong Shatin. KGD Group has developed into a supporting Industrial company integrating development, Manufacture and Purchasing services. Strong technical force, complete production equipment, complete testing. The main products : Die-cut parts of various mobile phones, tablet and other products, as well as precision copper, Stainless steel and Insulating Material Stamping Parts, aluminum alloy castings, zinc alloy die castings, industrial plastic bags, stretch film, etc. The company adopts the most advanced international production equipment and testing equipment to provide customers with the best quality products. The company has passed ISO 9001 and ISO 14001 certification, and is a major supplier of professional fine blanking and die-cutting products in the international market.',
        'company-intro': 'KGD Group has developed into a comprehensive industrial company integrating development, manufacturing, and procurement services. The company uses the most advanced international production and testing equipment to provide customers with the highest quality products. It is a major supplier of professional precision stamping and die-cutting products in the international market.',
        'company-history-title': 'Development History',
        'history-2002-title': 'Company Establishment',
        'history-2002-content': 'Longcheer Technology was established in Shanghai, focusing on mobile communication product R&D and manufacturing.',
        'history-2010-title': 'Business Expansion',
        'history-2010-content': 'Successfully expanded smart terminal product lines, becoming a leading smart product solution provider.',
        'history-2020-title': 'Technology Innovation',
        'history-2020-content': 'Established global R&D centers, promoting innovative applications of cutting-edge technologies like 5G and AI.',
        'advantages-title': 'Core Advantages',
        'advantage-tech': 'Technology Innovation',
        'advantage-tech-content': 'Strong R&D team and advanced technology platform, continuously driving product innovation.',
        'advantage-manufacture': 'Smart Manufacturing',
        'advantage-manufacture-content': 'Advanced smart manufacturing systems ensuring product quality and production efficiency.',
        'advantage-global': 'Global Presence',
        'advantage-global-content': 'Global R&D, production and sales network serving customers worldwide.',
        'products-title': 'Products',
        'product1-title': 'Die Casting Mold',
        'product2-title': 'Stretch Film',
        'product3-title': 'Hardware Display',
        'product1-desc': 'High-precision die casting molds, widely used in the manufacturing of various industrial products, featuring excellent durability and precision.',
        'product2-desc': 'High-strength stretch film, suitable for packaging, protecting, and transporting various products, with excellent extensibility and toughness.',
        'product3-desc': "Diversified precision hardware parts, widely used in electronics, machinery, and other fields, meeting customers' diverse needs.",
        'culture-title': 'partnership',
        'culture-subtitle': 'partnership',
        'culture-vision': 'Our Vision',
        'culture-vision-content': 'To become a leading provider of smart products and services',
        'culture-mission': 'Our Mission',
        'culture-mission-content': 'Creating new value for society through technology',
        'culture-values': 'Core Values',
        'culture-values-content': 'Customer-centric, Value Contributors, Long-term Perspective',
        'career-title': 'Career Development',
        'career-subtitle': 'Growing Together with Longcheer',
        'career-philosophy': 'We advocate "Value Contributors First" and integrate it into talent evaluation, development, and incentive management activities. We have gradually formed a full-cycle talent management system based on qualification, performance evaluation, and compensation incentive systems, defining positions, levels, salaries, and promotion channels. Meanwhile, we use AI organization for personnel review and decision-making to enhance fairness and objectivity.',
        'career-development-title': 'Talent Development',
        'career-development-content': 'We will invest more resources in capability development. Longcheer Academy and 9 professional academies help campus recruits, new employees, and managers at all levels quickly integrate and excel, cultivating professionals across various fields. We are developing a more precise, systematic learning platform covering knowledge bases for all positions, creating a learning organization to help everyone grow together.',
        'career-plan-title': 'Development Plan',
        'career-plan-content': 'We will continue to promote the Active Water Plan, creating an internal market-oriented talent mobility mechanism, supporting job rotation for employees who have been in the same position for over three years, enhancing and enriching personnel capabilities through rotation.',
        'copyright': 'Copyright©2016 Shanghai Longcheer Technology Co., Ltd. All Rights Reserved',
        'smartphone-title': 'Smart Phone',
        'product-planning-title': 'Product Planning',
        'product-planning-content': 'New product development fully aligns with market demands, implementing user experience, appearance design, function optimization, and customized systems. We adjust product planning according to market dynamics, creating differentiated product positioning with craftsmanship.',
        'tech-innovation-title': 'Technical Innovation & R&D',
        'tech-innovation-content': 'Combining precision craftsmanship standards, polymer composite materials, intelligent algorithm design, innovative structures, and more personalized experiences. Through our independently developed diversified software systems, we achieve adaptive display and functional linkage.',
        'platform-title': 'Comprehensive Solution Platform',
        'platform-content': 'Creating full-platform solutions from entry-level to flagship, covering all mobile terminal needs, supporting rapid customized development and mass production.',
        'quality-title': 'Quality Management',
        'quality-content': 'Based on intelligent testing technology and industry standards for raw material inspection, with process analysis management and CQA improvement certification, ISO/IEC17025 laboratory and professional technical testing team, comprehensively improving product quality and service standards.',
        'esg-title': 'Sustainable Development & ESG',
        'esg-subtitle': 'SUSTAINABLE DEVELOPMENT & ESG',
        'esg-strategy-title': 'ESG Strategy and Mechanism',
        'esg-strategy-content': 'We are committed to integrating ESG concepts into corporate development strategy, promoting sustainable development through establishing a comprehensive ESG management system, creating long-term value for society.',
        'esg-governance-title': 'ESG Governance System',
        'governance-level-1': 'Strategic Level',
        'governance-level-1-content': 'Board of Directors takes full responsibility for ESG strategy and reporting',
        'governance-level-2': 'Management Level',
        'governance-level-2-content': 'ESG Committee is responsible for daily ESG management',
        'governance-level-3': 'Executive Level',
        'governance-level-3-content': 'Functional departments are responsible for specific ESG work execution',
        'esg-performance-title': '2024 Key Performance Overview',
        'performance-env': 'Environmental: Protecting Earth',
        'performance-env-1': '• 15% reduction in carbon emission intensity',
        'performance-env-2': '• 20% increase in renewable energy usage',
        'performance-env-3': '• 95% waste recycling rate',
        'performance-social': 'Social: Creating Value Together',
        'performance-social-1': '• 100% employee training coverage',
        'performance-social-2': '• 90% supplier ESG assessment coverage',
        'performance-social-3': '• 5 million RMB community investment',
        'performance-gov': 'Governance: Steady Development',
        'performance-gov-1': '• 40% board diversity ratio',
        'performance-gov-2': '• 100% anti-corruption training coverage',
        'performance-gov-3': '• Zero information security incidents',
        'esg-reports-title': 'Reports and Documents',
        'report-2024': 'Longcheer Technology ESG Report 2024',
        'download-report': 'Download Report',
        'contact-title': 'Contact Us',
        'contact-subtitle': 'CONTACT US',
        'contact-address-title': 'Address',
        'contact-address': 'Unit 6, 11/F, Wah Luen Industrial Centre, 10-14 Kwei Tei Street, Fo Tan, Shatin, N.T., Hong Kong',
        'contact-phone-title': 'Phone',
        'contact-phone': 'Tel.:(852)3188447, 31884564 Fax:(852)31884152',
        'contact-email-title': 'Email',
        'contact-email': 'kgd@kgdcor.com',
        'contact-form-title': 'Send Us a Message',
        'contact-submit': 'Send Message',
        'contact-name-placeholder': 'Your Name',
        'contact-email-placeholder': 'Your Email',
        'contact-subject-placeholder': 'Subject',
        'contact-message-placeholder': 'Your Message',
        'employee-dev-title': 'Employee Development',
        'dev-training': 'Training System',
        'dev-training-content': 'Comprehensive training system to support employee growth',
        'dev-career': 'Career Development',
        'dev-career-content': 'Clear promotion path to achieve career goals',
        'dev-environment': 'Work Environment',
        'dev-environment-content': 'Comfortable work environment to inspire innovation',
        'dev-benefits': 'Benefits',
        'dev-benefits-content': 'Competitive benefits to protect employee rights',
        'activities-title': 'Company Activities',
        'activity-team': 'Team Building',
        'activity-team-content': 'Rich team building activities to enhance team cohesion',
        'activity-culture': 'Cultural Activities',
        'activity-culture-content': 'Diverse cultural activities to enrich employee life',
        'activity-charity': 'Charity Activities',
        'activity-charity-content': 'Actively fulfill social responsibility and participate in public welfare',
        'culture-innovation': 'Innovation Culture',
        'culture-innovation-content': 'Encouraging innovative thinking, embracing change, continuously breaking through technical boundaries, creating greater value for customers.',
        'culture-innovation-1': '• Innovation Lab',
        'culture-innovation-2': '• Technical Seminars',
        'culture-innovation-3': '• Innovation Project Incubation',
        'culture-collaboration': 'Collaboration Culture',
        'culture-collaboration-content': 'Advocating open cooperation, cross-departmental synergy, building efficient teams, achieving common goals.',
        'culture-collaboration-1': '• Cross-departmental Projects',
        'culture-collaboration-2': '• Team Building Activities',
        'culture-collaboration-3': '• Knowledge Sharing Platform',
        'work-env-title': 'Work Environment',
        'env-office': 'Modern Office Environment',
        'env-office-content': 'Spacious and bright office space with advanced facilities, providing employees with a comfortable working environment.',
        'env-leisure': 'Leisure Space',
        'env-leisure-content': 'Gym, lounge, coffee bar and other leisure facilities, allowing employees to fully relax after work.',
        'env-lab': 'Innovation R&D Center',
        'env-lab-content': 'R&D laboratory equipped with advanced equipment, providing the best environment for technological innovation.',
        'main-equipment-title': 'Main Equipment',
        'service-flow-title': 'Service Process',
        'service-step1-title': 'Product Design',
        'service-step1-desc': 'Professional product design according to customer requirements.',
        'service-step2-title': 'Sample Delivery',
        'service-step2-desc': 'Provide samples for customer confirmation.',
        'service-step3-title': 'Sign Approval',
        'service-step3-desc': 'Sign approval after customer confirms the sample.',
        'service-step4-title': 'Sign Contract',
        'service-step4-desc': 'Both parties sign a formal cooperation contract.',
        'service-step5-title': 'Production Supervision',
        'service-step5-desc': 'Supervise the production progress and quality throughout the process.',
        'service-step6-title': 'Quality Assurance',
        'service-step6-desc': 'Strict quality inspection to ensure product quality.',
        'service-step7-title': 'Logistics',
        'service-step7-desc': 'Support sea, air, and land transportation.',
        'service-step8-title': 'After-sales Service',
        'service-step8-desc': 'Dedicated personnel follow up and respond to customer needs in time.',
        'footer-company-name': 'KGD (H.K.) Corporation Limited',
        'footer-contact-info': 'Tel.:(852)3188447, 31884564 Fax:(852)31884152',
        'footer-email': 'kgd@kgdcor.com',
        'footer-address': 'Unit 6, 11/F, Wah Luen Industrial Centre, 10-14 Kwei Tei Street, Fo Tan, Shatin, N.T., Hong Kong',
        'footer-quick-links': 'Quick Links',
        'footer-copyright': 'All Rights Reserved'
    }
};

// 切换语言函数
function switchLanguage(lang) {
    document.documentElement.lang = lang;
    
    // 更新文本内容
    const elements = document.querySelectorAll('[data-lang]');
    elements.forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // 更新placeholder
    const placeholderElements = document.querySelectorAll('[data-lang-placeholder]');
    placeholderElements.forEach(element => {
        const key = element.getAttribute('data-lang-placeholder');
        if (translations[lang] && translations[lang][key]) {
            element.placeholder = translations[lang][key];
        }
    });
    
    // 保存语言选择到本地存储
    localStorage.setItem('preferred-language', lang);
}

// 初始化AOS动画库
document.addEventListener('DOMContentLoaded', function() {
    // 初始化AOS
    AOS.init({
        duration: 800,
        once: true,
        offset: 100
    });
    
    // 检查并应用保存的语言设置
    const savedLang = localStorage.getItem('preferred-language');
    if (savedLang) {
        switchLanguage(savedLang);
    }
    
    // 滚动时触发动画
    window.addEventListener('scroll', function() {
        AOS.refresh();
    });
}); 